// <auto-generated />
using System;
using Creation_de_personnage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Creation_de_personnage.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Creation_de_personnage.Models.Personnage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Armure")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Degats")
                        .HasColumnType("int");

                    b.Property<int?>("NombreVictime")
                        .HasColumnType("int");

                    b.Property<int?>("PointDeVie")
                        .HasColumnType("int");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personnages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Armure = 4,
                            DateCreation = new DateTime(2024, 1, 19, 10, 2, 27, 945, DateTimeKind.Local).AddTicks(7560),
                            Degats = 6,
                            NombreVictime = 0,
                            PointDeVie = 12,
                            Pseudo = "AlexHam"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
